// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drivers.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDriver = `-- name: CreateDriver :exec
INSERT INTO drivers (id, name, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateDriverParams struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Status    DriverStatus       `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDriver(ctx context.Context, arg CreateDriverParams) error {
	_, err := q.db.Exec(ctx, createDriver,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getDriverByID = `-- name: GetDriverByID :one
SELECT id, name, status, created_at, updated_at
FROM drivers
WHERE id = $1 LIMIT 1
`

type GetDriverByIDRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Status    DriverStatus       `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetDriverByID(ctx context.Context, id uuid.UUID) (GetDriverByIDRow, error) {
	row := q.db.QueryRow(ctx, getDriverByID, id)
	var i GetDriverByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDriverLocation = `-- name: UpdateDriverLocation :exec
UPDATE drivers
SET current_location = ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography, 
    updated_at = $3
WHERE id = $4
`

type UpdateDriverLocationParams struct {
	Lon       float64            `json:"lon"`
	Lat       float64            `json:"lat"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        uuid.UUID          `json:"id"`
}

// We use ST_SetSRID and ST_MakePoint to let Postgres handle the complex spatial data creation.
func (q *Queries) UpdateDriverLocation(ctx context.Context, arg UpdateDriverLocationParams) error {
	_, err := q.db.Exec(ctx, updateDriverLocation,
		arg.Lon,
		arg.Lat,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateDriverStatus = `-- name: UpdateDriverStatus :exec
UPDATE drivers
SET status = $1, updated_at = $2
WHERE id = $3
`

type UpdateDriverStatusParams struct {
	Status    DriverStatus       `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateDriverStatus(ctx context.Context, arg UpdateDriverStatusParams) error {
	_, err := q.db.Exec(ctx, updateDriverStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
