// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DriverStatus string

const (
	DriverStatusAVAILABLE DriverStatus = "AVAILABLE"
	DriverStatusONTRIP    DriverStatus = "ON_TRIP"
	DriverStatusOFFLINE   DriverStatus = "OFFLINE"
)

func (e *DriverStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DriverStatus(s)
	case string:
		*e = DriverStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DriverStatus: %T", src)
	}
	return nil
}

type NullDriverStatus struct {
	DriverStatus DriverStatus `json:"driver_status"`
	Valid        bool         `json:"valid"` // Valid is true if DriverStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDriverStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DriverStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DriverStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDriverStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DriverStatus), nil
}

type Driver struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Status          DriverStatus       `json:"status"`
	CurrentLocation interface{}        `json:"current_location"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
