// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDriver(ctx context.Context, arg CreateDriverParams) error
	GetDriverByID(ctx context.Context, id uuid.UUID) (GetDriverByIDRow, error)
	// We use ST_SetSRID and ST_MakePoint to let Postgres handle the complex spatial data creation.
	UpdateDriverLocation(ctx context.Context, arg UpdateDriverLocationParams) error
	UpdateDriverStatus(ctx context.Context, arg UpdateDriverStatusParams) error
}

var _ Querier = (*Queries)(nil)
